server:
  port: 8000

spring:
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USER}
      password: ${NEO4J_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui

trustedparty:
  base-url: ${TP_BASE_URL}

app:
  id: ${APP_ID}
  fqdn: ${APP_FQDN}
  tpFqdn: ${APP_TP_FQDN}
  disableTrustedParty: ${APP_DISABLE_TRUSTED_PARTY:false}