server:
  port: 8020

spring:
  datasource:
    url: ${TP_DB_URL}
    username: ${TP_DB_USER}
    password: ${TP_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui

app:
  id: ${TP_ID}
  fqdn: ${TP_FQDN}
  trustedCertsDirPath: ${TP_TRUSTED_CERTS_DIR}
  publicCertPath: ${TP_PUBLIC_CERT_PATH}
  privateKeyPath: ${TP_PRIVATE_KEY_PATH}